### ISSUE TITLE
Create Friends Page 

### ISSUE THREAD

**Issue by welschoff** [welschoff/watchnext#7]
<img width="240" alt="Screenshot 2021-11-23 at 15 35 08" src="https://user-images.githubusercontent.com/90267486/143043844-1da93a92-5387-4b4d-9c98-2008f52d526a.png">

### Tasks

- [ ] Show all my friends
- [ ] Create a search function to add new friends
- [ ] If I click on a friend I want to navigate to his/her Watchlist
